[dga]
	dmft_input="dmft_input_large.hdf5"
	max_iter=1
	asymp = "dual" # ['bubble', 'bare-u', 'dual']
	nouter = 500
	file_name="res"
	lambda_type="Pauli"
	lambda_decay=2
	mixing = 0.5

[lattice]
	ts = [1.0, 0.0]
	irrbz = true
	nk = 8
	nq = 8
	
[phonons]
	g02 = 0.1
	w0 = 1.0

